"""LLC small-signal, sampled-data, complete-loop and C99 export utilities."""

from .linearize import (
    ControlInputKind,
    LinearizedPlant,
    SISOTransferFunction,
    linearize_dynamic_phasor,
)
from .discretize import DiscretePlant, DifferenceEquation, discretize_zoh
from .analysis import SmallSignalAnalysis, build_small_signal_analysis
from .export_c import export_c99_plant_model, export_c99_state_space_model
from .digital_loop import (
    ADCSamplingConfig,
    AnalogSenseConfig,
    CommandTimingConfig,
    ControllerKind,
    DelayEnvelope,
    DigitalLoopAnalysis,
    DigitalTransferFunction,
    FMLUTMode,
    FMOperatingPoint,
    FrequencyModulatorLUT,
    PIControllerConfig,
    PIFControllerConfig,
    PWMCountMode,
    StabilityMargins,
    TwoP2ZControllerConfig,
    build_digital_loop_analysis,
    calculate_stability_margins,
    evaluate_fm_operating_point,
    export_controller_c99,
    export_digital_loop_analysis,
)
from .smart_control import (
    LoopModel,
    TimingModel,
    build_loop_model,
    compute_phase_budget,
    compute_stability_metrics,
    verify_exact_hz_float32,
)

__all__ = [
    "ADCSamplingConfig",
    "AnalogSenseConfig",
    "CommandTimingConfig",
    "ControlInputKind",
    "ControllerKind",
    "DelayEnvelope",
    "DigitalLoopAnalysis",
    "DigitalTransferFunction",
    "DiscretePlant",
    "DifferenceEquation",
    "FMLUTMode",
    "FMOperatingPoint",
    "FrequencyModulatorLUT",
    "LinearizedPlant",
    "PIControllerConfig",
    "PIFControllerConfig",
    "PWMCountMode",
    "SISOTransferFunction",
    "SmallSignalAnalysis",
    "StabilityMargins",
    "TwoP2ZControllerConfig",
    "build_digital_loop_analysis",
    "build_small_signal_analysis",
    "calculate_stability_margins",
    "discretize_zoh",
    "evaluate_fm_operating_point",
    "export_c99_plant_model",
    "export_c99_state_space_model",
    "export_controller_c99",
    "export_digital_loop_analysis",
    "linearize_dynamic_phasor",
    "LoopModel",
    "TimingModel",
    "build_loop_model",
    "compute_phase_budget",
    "compute_stability_metrics",
    "verify_exact_hz_float32",
]
