"""V8 multi-fidelity LLC steady-state analysis package."""

from .export import export_multifidelity_analysis, write_multifidelity_markdown
from .fha import solve_fha
from .fha_td_validation import (
    DeviationResult,
    FhaCredibility,
    FhaTdPointValidation,
    FhaTdValidationReport,
    FhaValidityCell,
    FhaValidityMap,
    ModelValidity,
    ValidityThresholds,
    build_fha_validity_map,
    compare_fha_td_metrics,
    critical_requests_from_envelope,
    default_critical_requests,
    validate_fha_against_time_domain,
    validate_fha_td,
    validate_fha_td_point,
)
from .engineering_validation import EngineeringEvidenceReport, run_engineering_validation
from .golden import GoldenSolverConfig, LLCGoldenSolver, solve_multifidelity
from .harmonic_balance import (
    HarmonicBalanceConfig,
    HarmonicBalanceConvergenceError,
    HarmonicBalanceNativeSolution,
    HarmonicConvergenceStep,
    MultiHarmonicLLCSolver,
    exact_rectifier_projection,
    extract_peak_phasors,
    find_trigonometric_zero_crossings,
    odd_harmonics,
    solve_harmonic_balance,
    synthesize_real_waveform,
)
from .time_domain import TimeDomainConfig, TimeDomainNativeSolution, solve_time_domain
from .complementarity import ComplementarityTimeDomainConfig, solve_complementarity_time_domain
from .types import (
    FidelityLevel,
    LLCAnalysisRequest,
    LLCModelResult,
    ModelComparisonRow,
    ModelMetrics,
    MultiFidelityAnalysis,
    SolverConvergence,
)

__all__ = [
    "DeviationResult",
    "FidelityLevel",
    "FhaTdPointValidation",
    "FhaTdValidationReport",
    "GoldenSolverConfig",
    "HarmonicBalanceConfig",
    "HarmonicBalanceConvergenceError",
    "HarmonicBalanceNativeSolution",
    "HarmonicConvergenceStep",
    "LLCAnalysisRequest",
    "LLCGoldenSolver",
    "LLCModelResult",
    "ModelComparisonRow",
    "ModelMetrics",
    "ModelValidity",
    "MultiFidelityAnalysis",
    "MultiHarmonicLLCSolver",
    "SolverConvergence",
    "TimeDomainConfig",
    "ComplementarityTimeDomainConfig",
    "TimeDomainNativeSolution",
    "ValidityThresholds",
    "build_fha_validity_map",
    "compare_fha_td_metrics",
    "critical_requests_from_envelope",
    "default_critical_requests",
    "exact_rectifier_projection",
    "export_multifidelity_analysis",
    "extract_peak_phasors",
    "find_trigonometric_zero_crossings",
    "odd_harmonics",
    "run_engineering_validation",
    "solve_fha",
    "solve_harmonic_balance",
    "solve_multifidelity",
    "solve_time_domain",
    "solve_complementarity_time_domain",
    "synthesize_real_waveform",
    "validate_fha_against_time_domain",
    "validate_fha_td",
    "validate_fha_td_point",
    "write_multifidelity_markdown",
    "EngineeringEvidenceReport",
    "FhaCredibility",
    "FhaValidityCell",
    "FhaValidityMap",
]
